const universities = {
  Federal: [
    "Abubakar Tafawa Balewa University, Bauchi",
    "Ahmadu Bello University, Zaria",
    "Bayero University, Kano",
    "Federal University Gashua, Yobe",
    "Federal University of Petroleum Resources, Effurun",
    "Federal University of Technology, Akure",
    "Federal University of Technology, Minna",
    "Federal University of Technology, Owerri",
    "Federal University, Dutse, Jigawa State",
    "Federal University, Dutsin-Ma, Katsina",
    "Federal University, Kashere, Gombe State",
    "Federal University, Lafia, Nasarawa State",
    "Federal University, Lokoja, Kogi State",
    "Alex Ekwueme University, Ndufu-Alike, Ebonyi State",
    "Federal University, Otuoke, Bayelsa",
    "Federal University, Oye-Ekiti, Ekiti State",
    "Federal University, Wukari, Taraba State",
    "Federal University, Birnin Kebbi",
    "Federal University, Gusau Zamfara",
    "Michael Okpara University of Agricultural Umudike",
    "Modibbo Adama University of Technology, Yola",
    "National Open University of Nigeria, Abuja",
    "Nigeria Police Academy Wudil",
    "Nigerian Defence Academy Kaduna",
    "Nnamdi Azikiwe University, Awka",
    "Obafemi Awolowo University,Ile-Ife",
    "University of Abuja, Gwagwalada",
    "Federal University of Agriculture, Abeokuta",
    "Joseph Sarwuan Tarka University, Makurdi",
    "University of Benin",
    "University of Calabar",
    "University of Ibadan",
    "University of Ilorin",
    "University of Jos",
    "University of Lagos",
    "University of Maiduguri",
    "University of Nigeria, Nsukka",
    "University of Port-Harcourt",
    "University of Uyo",
    "Usumanu Danfodiyo University",
    "Nigerian Maritime University Okerenkoko, Delta State",
    "Air Force Institute of Technology, Kaduna",
    "Nigerian Army University Biu",
    "Federal University of Health Sciences, Otukpo, Benue State",
    "Federal University of Agriculture, Zuru, Kebbi State",
    "Federal University of Technology, Babura, Jigawa State",
    "Federal University of Technology, Ikot Abasi, Akwa Ibom State",
    "Federal University of Health Sciences, Azare, Bauchi State",
    "Federal University of Health Sciences, Ila Orangun, Osun State",
    "David Nweze Umahi Federal University of Medical Sciences, Uburu",
    "Admiralty University Ibusa, Delta State",
    "Federal University of Transportation Daura, Katsina",
    "African Aviation and Aerospace University",
    "National University of Science and Technology, Abuja",
    "Federal University of Agriculture Bassam-Biri, Bayelsa",
    "Federal University of Health Sciences Kwale, Delta State",
    "Federal University of Health Sciences, Katsina",
    "Federal University of Agriculture, Mubi",
    "Federal University of Education, Zaria, Kaduna State",
    "Alvan Ikoku Federal University of Education, Owerri, Imo State",
    "Federal University of Education, Kano",
    "Adeyemi Federal University of Education, Ondo",
    "Federal University of Allied Health Sciences, Enugu",
    "Federal University of Medicine and Medical Sciences, Abeokuta",
    "Federal University of Education Pankshin, Plateau State",
    "Federal University of Education Kontagora, Niger State",
    "University of Maritime Studies, Oron, Akwa Ibom State",
    "Federal University of Environment and Technology, Tai Town, Ogoniland, Rivers State",
    "Federal University of Applied Sciences, Kachia, Kaduna State",
    "Tai Solarin Federal University of Education, Ijagun, Ijebu Ode",
    "Federal University of Agriculture and Developmental Studies, Iragbuji, Osun State",
    "Federal University of Technology and Environmental Studies, Iyin-Ekiti, Ekiti State."
  ],
  State: [
    "Abia State University, Uturu",
    "Adamawa State University Mubi",
    "Adekunle Ajasin University, Akungba",
    "Akwa Ibom State University, Ikot Akpaden",
    "Ambrose Alli University, Ekpoma",
    "Chukwuemeka Odumegwu Ojukwu University, Uli",
    "Bauchi State University, Gadau",
    "Benue State University, Makurdi",
    "Yobe State University, Damaturu",
    "University of Cross River State, Calabar",
    "Delta State University Abraka",
    "Ebonyi State University, Abakaliki",
    "Ekiti State University",
    "Enugu State University of Science and Technology, Enugu",
    "Gombe State Univeristy, Gombe",
    "Ibrahim Badamasi Babangida University, Lapai",
    "Ignatius Ajuru University of Education,Rumuolumeni",
    "Imo State University, Owerri",
    "Sule Lamido University, Kafin Hausa, Jigawa",
    "Kaduna State University, Kaduna",
    "Aliko Dangote university of Science & Technology, Wudil",
    "Kebbi State University of Science and Technology, Aliero",
    "Prince Abubakar Audu University Anyigba",
    "Kwara State University, Ilorin",
    "Ladoke Akintola University of Technology, Ogbomoso",
    "Olusegun Agagu University of Sc. & Tech., Okitipupa, Ondo",
    "Rivers State University",
    "Olabisi Onabanjo University, Ago Iwoye",
    "Lagos State University, Ojo",
    "Niger Delta University Yenagoa",
    "Nasarawa State University Keffi",
    "Plateau State University Bokkos",
    "Umar Musa Yar' Adua University Katsina",
    "Osun State University Osogbo",
    "Taraba State University, Jalingo",
    "Sokoto State University",
    "Yusuf Maitama Sule University Kano",
    "First Technical University Ibadan",
    "University of Medical Sciences, Ondo City, Ondo State",
    "Edo State University Uzairue",
    "Kingsley Ozumba Mbadiwe University Ogboko, Imo State",
    "University of Africa Toru Orua, Bayelsa State",
    "Bornu State University, Maiduguri",
    "Moshood Abiola University of Science and Technology Abeokuta",
    "Gombe State University of Science and Technology",
    "Zamfara State University",
    "Bayelsa Medical University",
    "University of Agriculture and Environmental Sciences Umuagwo, Imo State",
    "Confluence University of Science and Technology Osara, Kogi",
    "University of Delta, Agbor",
    "Delta University of Science and Technology, Ozoro",
    "Dennis Osadebe University, Asaba",
    "Bamidele Olumilua University of Science and Technology Ikere, Ekiti State",
    "Lagos State University of Education, Ijanikin",
    "Lagos State University of Science and Technology Ikorodu",
    "Shehu Shagari University of Education, Sokoto",
    "State University of Medical and Applied Sciences, Igbo-Eno, Enugu",
    "University of Ilesa, Osun State",
    "Emanuel Alayande University of Education Oyo",
    "Kogi State University, Kabba",
    "AbdulKadir Kure University, Minna Niger State",
    "Kwara State University of Education, Ilorin, Kwara State",
    "Abdulsalam Abubakar University of Agriculture and Climate Action, Mokwa, Niger State",
    "Ebonyi State University of ICT, Science and Technology, Oferekpe, Ebonyi State",
    "Cross River University of Education and Entrepeneurship, Akampa, Cross River State",
    "Benue State Univerity of Agriculture Science and Technology"
  ],
  Private: [
    "Achievers University, Owo",
    "Adeleke University, Ede",
    "Afe Babalola University, Ado-Ekiti - Ekiti State",
    "Ajayi Crowther University, Ibadan",
    "Al-Hikmah University, Ilorin",
    "Al-Qalam University, Katsina",
    "American University of Nigeria, Yola",
    "Augustine University",
    "Babcock University, Ilishan-Remo",
    "Baze University",
    "Bells University of Technology, Otta",
    "Benson Idahosa University, Benin City",
    "Bingham University, New Karu",
    "Bowen University, Iwo",
    "Caleb University, Lagos",
    "Caritas University, Enugu",
    "Chrisland University",
    "Covenant University, Ota",
    "Crawford University, Igbesa",
    "Crescent University",
    "Edwin Clark University, Kaigbodo",
    "Elizade University, Ilara-Mokin",
    "Evangel University, Akaeze",
    "Fountain University, Oshogbo",
    "Godfrey Okoye University, Ugwuomu-Nike - Enugu State",
    "Gregory University, Uturu",
    "Hallmark University, Ijebi Itele, Ogun",
    "Hezekiah University, Umudi",
    "Igbinedion University, Okada",
    "Joseph Ayo Babalola University, Ikeji-Arakeji",
    "Kings University, Ode Omu",
    "Kwararafa University, Wukari",
    "Landmark University, Omu-Aran",
    "Lead City University, Ibadan",
    "Madonna University, Okija",
    "Mcpherson University, Seriki Sotayo, Ajebo",
    "Micheal & Cecilia Ibru University",
    "Mountain Top University",
    "Nile University of Nigeria, Abuja",
    "Novena University, Ogume",
    "Obong University, Obong Ntak",
    "Oduduwa University, Ipetumodu - Osun State",
    "Pan-Atlantic University, Lagos",
    "Paul University, Awka - Anambra State",
    "Renaissance University, Enugu",
    "Rhema University, Obeama-Asa, Rivers State",
    "Ritman University, Ikot Ekpene, Akwa Ibom State",
    "Salem University, Lokoja",
    "Samuel Adegboyega University, Ogwa, Edo State",
    "Southwestern University, Okun Owa",
    "Tansian University, Umunya",
    "Veritas University, Abuja",
    "Wellspring University, Evbuobanosa - Edo State",
    "Wesley University, Ondo",
    "Western Delta University, Oghara Delta State",
    "Christopher University, Mowe",
    "Kola Daisi University, Ibadan, Oyo State",
    "Anchor University Ayobo Lagos State",
    "Dominican University Ibadan Oyo State",
    "Legacy University, Okija Anambra State",
    "Arthur Jarvis University Akpoyubo Cross river State",
    "Crown Hill University Eiyenkorin, Kwara State",
    "Coal City University Enugu State",
    "Clifford University Owerrinta Abia State",
    "Spiritan University, Nneochi Abia State",
    "Precious Cornerstone University, Oyo",
    "PAMO University of Medical Sciences, Portharcourt",
    "Atiba University Oyo",
    "Eko University of Medical and Health Sciences Ijanikin, Lagos",
    "Skyline University, Kano",
    "Greenfield University, Kaduna",
    "Dominion University Ibadan, Oyo State",
    "Trinity University Ogun State",
    "Westland University Iwo, Osun State",
    "Topfaith University, Mkpatak, Akwa Ibom State",
    "Thomas Adewumi University, Oko, Kwara State",
    "Maranatha University, Mgbidi, Imo State",
    "Ave Maria University, Piyanko, Nasarawa State",
    "Al-Istiqama University, Sumaila, Kano State",
    "Mudiame University, Irrua, Edo State",
    "Havilla University, Nde-Ikom, Cross River State",
    "Claretian University of Nigeria, Nekede, Imo State",
    "NOK University, Kachia, Kaduna State",
    "Karl-Kumm University, Vom, Plateau State",
    "James Hope University, Lagos, Lagos State",
    "Maryam Abacha American University of Nigeria, Kano State",
    "Capital City University, Kano State",
    "Ahman Pategi University, Patigi, Kwara State",
    "University of Offa, Kwara State",
    "Mewar International University, Masaka, Nasarawa State",
    "Edusoko University, Bida, Niger State",
    "Philomath University, Kuje, Abuja",
    "Khalifa Isiyaku Rabiu University, Kano",
    "Sports University, Idumuje, Ugboko, Delta State",
    "Prime Polytechnic University, Kogi State",
    "Pen Resource University, Gombe",
    "Al-Muhibbah Open University, Abuja",
    "Miva Open University, Abuja FCT",
    "Iconic Open University, Sokoto State",
    "West Midlands Open University, Ibadan, Oyo State",
    "Wigwe University, Isiokpo Rivers State",
    "Hensard University, Toru-Orua, Sagbama, Bayelsa State",
    "Phoenix University, Agwada, Nasarawa State",
    "Amaj University, Kwali, Abuja",
    "British Canadian University, Obufu Cross River State",
    "Gerar University of Medical Science Imope Ijebu, Ogun State.",
    "Canadian University of Nigeria, Abuja",
    "Franco British International University, Kaduna State",
    "Huda University, Gusau, Zamafara State",
    "Azman University, Kano State",
    "Vision University, Ikogbo, Ogun State",
    "Amadeus University, Amizi, Abia State",
    "PeaceLand University, Enugu State",
    "Maduka University, Ekwegbe, Enugu State",
    "Lux Mundi University Umuahia, Abia State",
    "Aletheia University, Ago-Iwoye Ogun State",
    "Sam Maris University, Ondo",
    "Muhammad Kamalud University Kwara",
    "Rayhaan University, Kebbi",
    "NorthWest University Sokoto State",
    "The Duke Medical University, Calabar, Cross River State",
    "Shanahan University Onitsha, Anambra State",
    "Venite University, Iloro-Ekiti, Ekiti State",
    "Elrazi Medical University Yargaya University, Kano State",
    "University on the Niger, Umunya, Anambra state",
    "Hillside University of Science and Technology, Okemisi, Ekiti State",
    "Lighthouse University, Evbobanosa, Edo State",
    "African University of Economics, FCT, Abuja",
    "New City University, Ayetoro, Ogun State",
    "University of Fortune, Igbotako, Ondo State",
    "Eranova University, Abuja",
    "Minaret University, Ikirun, Osun State",
    "Abdulrasaq Abubakar Toyin University, Oke-Ogba, Ganmo, Ilorin, Kwara State",
    "Southern Atlantic University, Uyo, Akwa Ibom State",
    "Lens University, Ilemona, Kwara State",
    "Monarch University, Iyesi-Ota, Ogun State",
    "Tonine Iredia University of Communication, Benin City, Edo State",
    "Isaac Balami University of Aeronautics and Management, Lagos State",
    "Kevin Eze University, Mgbowo, Enugu State"
  ]
};





const polytechnicsAndCollege = {
     Federal: [

     ],
     State: [

     ],
     Private: [
      
     ]
}
